/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ComiteRouteImport } from './routes/comite'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExpedientesIndexRouteImport } from './routes/expedientes.index'
import { Route as ComiteIndexRouteImport } from './routes/comite.index'
import { Route as ExpedientesNuevoRouteImport } from './routes/expedientes.nuevo'
import { Route as ExpedientesIdRouteImport } from './routes/expedientes.$id'
import { Route as ComiteIdRouteImport } from './routes/comite.$id'
import { Route as ApiIaCompletarRouteImport } from './routes/api/ia/completar'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ComiteRoute = ComiteRouteImport.update({
  id: '/comite',
  path: '/comite',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpedientesIndexRoute = ExpedientesIndexRouteImport.update({
  id: '/expedientes/',
  path: '/expedientes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComiteIndexRoute = ComiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ComiteRoute,
} as any)
const ExpedientesNuevoRoute = ExpedientesNuevoRouteImport.update({
  id: '/expedientes/nuevo',
  path: '/expedientes/nuevo',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpedientesIdRoute = ExpedientesIdRouteImport.update({
  id: '/expedientes/$id',
  path: '/expedientes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ComiteIdRoute = ComiteIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ComiteRoute,
} as any)
const ApiIaCompletarRoute = ApiIaCompletarRouteImport.update({
  id: '/api/ia/completar',
  path: '/api/ia/completar',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/comite': typeof ComiteRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/comite/$id': typeof ComiteIdRoute
  '/expedientes/$id': typeof ExpedientesIdRoute
  '/expedientes/nuevo': typeof ExpedientesNuevoRoute
  '/comite/': typeof ComiteIndexRoute
  '/expedientes/': typeof ExpedientesIndexRoute
  '/api/ia/completar': typeof ApiIaCompletarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/comite/$id': typeof ComiteIdRoute
  '/expedientes/$id': typeof ExpedientesIdRoute
  '/expedientes/nuevo': typeof ExpedientesNuevoRoute
  '/comite': typeof ComiteIndexRoute
  '/expedientes': typeof ExpedientesIndexRoute
  '/api/ia/completar': typeof ApiIaCompletarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/comite': typeof ComiteRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/comite/$id': typeof ComiteIdRoute
  '/expedientes/$id': typeof ExpedientesIdRoute
  '/expedientes/nuevo': typeof ExpedientesNuevoRoute
  '/comite/': typeof ComiteIndexRoute
  '/expedientes/': typeof ExpedientesIndexRoute
  '/api/ia/completar': typeof ApiIaCompletarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clientes'
    | '/comite'
    | '/dashboard'
    | '/login'
    | '/comite/$id'
    | '/expedientes/$id'
    | '/expedientes/nuevo'
    | '/comite/'
    | '/expedientes/'
    | '/api/ia/completar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clientes'
    | '/dashboard'
    | '/login'
    | '/comite/$id'
    | '/expedientes/$id'
    | '/expedientes/nuevo'
    | '/comite'
    | '/expedientes'
    | '/api/ia/completar'
  id:
    | '__root__'
    | '/'
    | '/clientes'
    | '/comite'
    | '/dashboard'
    | '/login'
    | '/comite/$id'
    | '/expedientes/$id'
    | '/expedientes/nuevo'
    | '/comite/'
    | '/expedientes/'
    | '/api/ia/completar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientesRoute: typeof ClientesRoute
  ComiteRoute: typeof ComiteRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  ExpedientesIdRoute: typeof ExpedientesIdRoute
  ExpedientesNuevoRoute: typeof ExpedientesNuevoRoute
  ExpedientesIndexRoute: typeof ExpedientesIndexRoute
  ApiIaCompletarRoute: typeof ApiIaCompletarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comite': {
      id: '/comite'
      path: '/comite'
      fullPath: '/comite'
      preLoaderRoute: typeof ComiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expedientes/': {
      id: '/expedientes/'
      path: '/expedientes'
      fullPath: '/expedientes/'
      preLoaderRoute: typeof ExpedientesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comite/': {
      id: '/comite/'
      path: '/'
      fullPath: '/comite/'
      preLoaderRoute: typeof ComiteIndexRouteImport
      parentRoute: typeof ComiteRoute
    }
    '/expedientes/nuevo': {
      id: '/expedientes/nuevo'
      path: '/expedientes/nuevo'
      fullPath: '/expedientes/nuevo'
      preLoaderRoute: typeof ExpedientesNuevoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expedientes/$id': {
      id: '/expedientes/$id'
      path: '/expedientes/$id'
      fullPath: '/expedientes/$id'
      preLoaderRoute: typeof ExpedientesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comite/$id': {
      id: '/comite/$id'
      path: '/$id'
      fullPath: '/comite/$id'
      preLoaderRoute: typeof ComiteIdRouteImport
      parentRoute: typeof ComiteRoute
    }
    '/api/ia/completar': {
      id: '/api/ia/completar'
      path: '/api/ia/completar'
      fullPath: '/api/ia/completar'
      preLoaderRoute: typeof ApiIaCompletarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ComiteRouteChildren {
  ComiteIdRoute: typeof ComiteIdRoute
  ComiteIndexRoute: typeof ComiteIndexRoute
}

const ComiteRouteChildren: ComiteRouteChildren = {
  ComiteIdRoute: ComiteIdRoute,
  ComiteIndexRoute: ComiteIndexRoute,
}

const ComiteRouteWithChildren =
  ComiteRoute._addFileChildren(ComiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientesRoute: ClientesRoute,
  ComiteRoute: ComiteRouteWithChildren,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  ExpedientesIdRoute: ExpedientesIdRoute,
  ExpedientesNuevoRoute: ExpedientesNuevoRoute,
  ExpedientesIndexRoute: ExpedientesIndexRoute,
  ApiIaCompletarRoute: ApiIaCompletarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
