/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NormativaRouteImport } from './routes/normativa'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InstitucionalRouteImport } from './routes/institucional'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ComiteRouteImport } from './routes/comite'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as AlertasRouteImport } from './routes/alertas'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExpedientesIndexRouteImport } from './routes/expedientes.index'
import { Route as ComiteIndexRouteImport } from './routes/comite.index'
import { Route as ExpedientesNuevoRouteImport } from './routes/expedientes.nuevo'
import { Route as ExpedientesIdRouteImport } from './routes/expedientes.$id'
import { Route as ComiteIdRouteImport } from './routes/comite.$id'
import { Route as AdminDocumentosRouteImport } from './routes/admin/documentos'
import { Route as ApiRagEmbeberRouteImport } from './routes/api/rag/embeber'
import { Route as ApiRagApi_rag_procesarRouteImport } from './routes/api/rag/api_rag_procesar'
import { Route as ApiRagApi_rag_consultarRouteImport } from './routes/api/rag/api_rag_consultar'
import { Route as ApiPublicIpRouteImport } from './routes/api/public/ip'
import { Route as ApiIaCompletarRouteImport } from './routes/api/ia/completar'

const NormativaRoute = NormativaRouteImport.update({
  id: '/normativa',
  path: '/normativa',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitucionalRoute = InstitucionalRouteImport.update({
  id: '/institucional',
  path: '/institucional',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ComiteRoute = ComiteRouteImport.update({
  id: '/comite',
  path: '/comite',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertasRoute = AlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpedientesIndexRoute = ExpedientesIndexRouteImport.update({
  id: '/expedientes/',
  path: '/expedientes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComiteIndexRoute = ComiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ComiteRoute,
} as any)
const ExpedientesNuevoRoute = ExpedientesNuevoRouteImport.update({
  id: '/expedientes/nuevo',
  path: '/expedientes/nuevo',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpedientesIdRoute = ExpedientesIdRouteImport.update({
  id: '/expedientes/$id',
  path: '/expedientes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ComiteIdRoute = ComiteIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ComiteRoute,
} as any)
const AdminDocumentosRoute = AdminDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => AdminRoute,
} as any)
const ApiRagEmbeberRoute = ApiRagEmbeberRouteImport.update({
  id: '/api/rag/embeber',
  path: '/api/rag/embeber',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRagApi_rag_procesarRoute = ApiRagApi_rag_procesarRouteImport.update({
  id: '/api/rag/api_rag_procesar',
  path: '/api/rag/api_rag_procesar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRagApi_rag_consultarRoute = ApiRagApi_rag_consultarRouteImport.update({
  id: '/api/rag/api_rag_consultar',
  path: '/api/rag/api_rag_consultar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIpRoute = ApiPublicIpRouteImport.update({
  id: '/api/public/ip',
  path: '/api/public/ip',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIaCompletarRoute = ApiIaCompletarRouteImport.update({
  id: '/api/ia/completar',
  path: '/api/ia/completar',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/alertas': typeof AlertasRoute
  '/clientes': typeof ClientesRoute
  '/comite': typeof ComiteRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/institucional': typeof InstitucionalRoute
  '/login': typeof LoginRoute
  '/normativa': typeof NormativaRoute
  '/admin/documentos': typeof AdminDocumentosRoute
  '/comite/$id': typeof ComiteIdRoute
  '/expedientes/$id': typeof ExpedientesIdRoute
  '/expedientes/nuevo': typeof ExpedientesNuevoRoute
  '/comite/': typeof ComiteIndexRoute
  '/expedientes/': typeof ExpedientesIndexRoute
  '/api/ia/completar': typeof ApiIaCompletarRoute
  '/api/public/ip': typeof ApiPublicIpRoute
  '/api/rag/api_rag_consultar': typeof ApiRagApi_rag_consultarRoute
  '/api/rag/api_rag_procesar': typeof ApiRagApi_rag_procesarRoute
  '/api/rag/embeber': typeof ApiRagEmbeberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/alertas': typeof AlertasRoute
  '/clientes': typeof ClientesRoute
  '/dashboard': typeof DashboardRoute
  '/institucional': typeof InstitucionalRoute
  '/login': typeof LoginRoute
  '/normativa': typeof NormativaRoute
  '/admin/documentos': typeof AdminDocumentosRoute
  '/comite/$id': typeof ComiteIdRoute
  '/expedientes/$id': typeof ExpedientesIdRoute
  '/expedientes/nuevo': typeof ExpedientesNuevoRoute
  '/comite': typeof ComiteIndexRoute
  '/expedientes': typeof ExpedientesIndexRoute
  '/api/ia/completar': typeof ApiIaCompletarRoute
  '/api/public/ip': typeof ApiPublicIpRoute
  '/api/rag/api_rag_consultar': typeof ApiRagApi_rag_consultarRoute
  '/api/rag/api_rag_procesar': typeof ApiRagApi_rag_procesarRoute
  '/api/rag/embeber': typeof ApiRagEmbeberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/alertas': typeof AlertasRoute
  '/clientes': typeof ClientesRoute
  '/comite': typeof ComiteRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/institucional': typeof InstitucionalRoute
  '/login': typeof LoginRoute
  '/normativa': typeof NormativaRoute
  '/admin/documentos': typeof AdminDocumentosRoute
  '/comite/$id': typeof ComiteIdRoute
  '/expedientes/$id': typeof ExpedientesIdRoute
  '/expedientes/nuevo': typeof ExpedientesNuevoRoute
  '/comite/': typeof ComiteIndexRoute
  '/expedientes/': typeof ExpedientesIndexRoute
  '/api/ia/completar': typeof ApiIaCompletarRoute
  '/api/public/ip': typeof ApiPublicIpRoute
  '/api/rag/api_rag_consultar': typeof ApiRagApi_rag_consultarRoute
  '/api/rag/api_rag_procesar': typeof ApiRagApi_rag_procesarRoute
  '/api/rag/embeber': typeof ApiRagEmbeberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/alertas'
    | '/clientes'
    | '/comite'
    | '/dashboard'
    | '/institucional'
    | '/login'
    | '/normativa'
    | '/admin/documentos'
    | '/comite/$id'
    | '/expedientes/$id'
    | '/expedientes/nuevo'
    | '/comite/'
    | '/expedientes/'
    | '/api/ia/completar'
    | '/api/public/ip'
    | '/api/rag/api_rag_consultar'
    | '/api/rag/api_rag_procesar'
    | '/api/rag/embeber'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/alertas'
    | '/clientes'
    | '/dashboard'
    | '/institucional'
    | '/login'
    | '/normativa'
    | '/admin/documentos'
    | '/comite/$id'
    | '/expedientes/$id'
    | '/expedientes/nuevo'
    | '/comite'
    | '/expedientes'
    | '/api/ia/completar'
    | '/api/public/ip'
    | '/api/rag/api_rag_consultar'
    | '/api/rag/api_rag_procesar'
    | '/api/rag/embeber'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/alertas'
    | '/clientes'
    | '/comite'
    | '/dashboard'
    | '/institucional'
    | '/login'
    | '/normativa'
    | '/admin/documentos'
    | '/comite/$id'
    | '/expedientes/$id'
    | '/expedientes/nuevo'
    | '/comite/'
    | '/expedientes/'
    | '/api/ia/completar'
    | '/api/public/ip'
    | '/api/rag/api_rag_consultar'
    | '/api/rag/api_rag_procesar'
    | '/api/rag/embeber'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AlertasRoute: typeof AlertasRoute
  ClientesRoute: typeof ClientesRoute
  ComiteRoute: typeof ComiteRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  InstitucionalRoute: typeof InstitucionalRoute
  LoginRoute: typeof LoginRoute
  NormativaRoute: typeof NormativaRoute
  ExpedientesIdRoute: typeof ExpedientesIdRoute
  ExpedientesNuevoRoute: typeof ExpedientesNuevoRoute
  ExpedientesIndexRoute: typeof ExpedientesIndexRoute
  ApiIaCompletarRoute: typeof ApiIaCompletarRoute
  ApiPublicIpRoute: typeof ApiPublicIpRoute
  ApiRagApi_rag_consultarRoute: typeof ApiRagApi_rag_consultarRoute
  ApiRagApi_rag_procesarRoute: typeof ApiRagApi_rag_procesarRoute
  ApiRagEmbeberRoute: typeof ApiRagEmbeberRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/normativa': {
      id: '/normativa'
      path: '/normativa'
      fullPath: '/normativa'
      preLoaderRoute: typeof NormativaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institucional': {
      id: '/institucional'
      path: '/institucional'
      fullPath: '/institucional'
      preLoaderRoute: typeof InstitucionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comite': {
      id: '/comite'
      path: '/comite'
      fullPath: '/comite'
      preLoaderRoute: typeof ComiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alertas': {
      id: '/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof AlertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expedientes/': {
      id: '/expedientes/'
      path: '/expedientes'
      fullPath: '/expedientes/'
      preLoaderRoute: typeof ExpedientesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comite/': {
      id: '/comite/'
      path: '/'
      fullPath: '/comite/'
      preLoaderRoute: typeof ComiteIndexRouteImport
      parentRoute: typeof ComiteRoute
    }
    '/expedientes/nuevo': {
      id: '/expedientes/nuevo'
      path: '/expedientes/nuevo'
      fullPath: '/expedientes/nuevo'
      preLoaderRoute: typeof ExpedientesNuevoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expedientes/$id': {
      id: '/expedientes/$id'
      path: '/expedientes/$id'
      fullPath: '/expedientes/$id'
      preLoaderRoute: typeof ExpedientesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comite/$id': {
      id: '/comite/$id'
      path: '/$id'
      fullPath: '/comite/$id'
      preLoaderRoute: typeof ComiteIdRouteImport
      parentRoute: typeof ComiteRoute
    }
    '/admin/documentos': {
      id: '/admin/documentos'
      path: '/documentos'
      fullPath: '/admin/documentos'
      preLoaderRoute: typeof AdminDocumentosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/rag/embeber': {
      id: '/api/rag/embeber'
      path: '/api/rag/embeber'
      fullPath: '/api/rag/embeber'
      preLoaderRoute: typeof ApiRagEmbeberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rag/api_rag_procesar': {
      id: '/api/rag/api_rag_procesar'
      path: '/api/rag/api_rag_procesar'
      fullPath: '/api/rag/api_rag_procesar'
      preLoaderRoute: typeof ApiRagApi_rag_procesarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rag/api_rag_consultar': {
      id: '/api/rag/api_rag_consultar'
      path: '/api/rag/api_rag_consultar'
      fullPath: '/api/rag/api_rag_consultar'
      preLoaderRoute: typeof ApiRagApi_rag_consultarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ip': {
      id: '/api/public/ip'
      path: '/api/public/ip'
      fullPath: '/api/public/ip'
      preLoaderRoute: typeof ApiPublicIpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ia/completar': {
      id: '/api/ia/completar'
      path: '/api/ia/completar'
      fullPath: '/api/ia/completar'
      preLoaderRoute: typeof ApiIaCompletarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminDocumentosRoute: typeof AdminDocumentosRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDocumentosRoute: AdminDocumentosRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ComiteRouteChildren {
  ComiteIdRoute: typeof ComiteIdRoute
  ComiteIndexRoute: typeof ComiteIndexRoute
}

const ComiteRouteChildren: ComiteRouteChildren = {
  ComiteIdRoute: ComiteIdRoute,
  ComiteIndexRoute: ComiteIndexRoute,
}

const ComiteRouteWithChildren =
  ComiteRoute._addFileChildren(ComiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AlertasRoute: AlertasRoute,
  ClientesRoute: ClientesRoute,
  ComiteRoute: ComiteRouteWithChildren,
  DashboardRoute: DashboardRoute,
  InstitucionalRoute: InstitucionalRoute,
  LoginRoute: LoginRoute,
  NormativaRoute: NormativaRoute,
  ExpedientesIdRoute: ExpedientesIdRoute,
  ExpedientesNuevoRoute: ExpedientesNuevoRoute,
  ExpedientesIndexRoute: ExpedientesIndexRoute,
  ApiIaCompletarRoute: ApiIaCompletarRoute,
  ApiPublicIpRoute: ApiPublicIpRoute,
  ApiRagApi_rag_consultarRoute: ApiRagApi_rag_consultarRoute,
  ApiRagApi_rag_procesarRoute: ApiRagApi_rag_procesarRoute,
  ApiRagEmbeberRoute: ApiRagEmbeberRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
